### ISSUE TITLE
Too many redundant types of checks

### ISSUE THREAD

**Issue by westonganger** [fatkodima/data_checks#1]
I think the addition of different types of checks is a bit overkill. It seems to me that this library should simply have one or two types, `ensure_truthy` and maybe `ensure_falsey` though this is likely redundant, any, less, or more checks seem to be totally useless when you can do the same logic in an `ensure_no` block without having to know any gem specific dsl.

**Comment by fatkodima** [comment]
Thanks for the feedback, appreciated.

If we will have only `ensure_truthy`/`ensure_falsey`, it will be hard to let the user know which items failed the check.
For example, `ensure_no` will report failed entries to the user https://github.com/fatkodima/data_checks/blob/eb71c88fa303329a7f18082bfed575e37bcba962/lib/data_checks/ensure_no.rb#L17-L22
https://github.com/fatkodima/data_checks/blob/eb71c88fa303329a7f18082bfed575e37bcba962/lib/data_checks/notifiers/email_default_formatter.rb#L24-L30

Without this, the user will need to make extra moves and go the db and run the check manually. And it is possible this user is not a developer with production db access. 

But yes, if the user writes something like
```ruby
ensure_no :users_without_email do
  User.where(email: nil).count # note the scalar value is returned
end
```
then it will be less helpful.
